# Generated by Django 4.2 on 2025-04-30 09:14

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('housing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('price', models.IntegerField()),
                ('bedrooms', models.IntegerField()),
                ('bathrooms', models.DecimalField(decimal_places=1, max_digits=2)),
                ('sqft', models.IntegerField()),
                ('main', models.ImageField(upload_to='listing')),
                ('photo1', models.ImageField(blank=True, null=True, upload_to='listing')),
                ('photo2', models.ImageField(blank=True, null=True, upload_to='listing')),
                ('photo3', models.ImageField(blank=True, null=True, upload_to='listing')),
                ('photo4', models.ImageField(blank=True, null=True, upload_to='listing')),
                ('listing_id', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('is_published', models.BooleanField(default=True)),
                ('posted', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('sale', 'For Sale'), ('rent', 'For Rent')], default='sale', max_length=10)),
                ('photo', models.ImageField(upload_to='property')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.PositiveIntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='housing.profile')),
            ],
        ),
        migrations.CreateModel(
            name='SingleListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('subtotal', models.PositiveIntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.listing')),
                ('userlisting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.userlisting')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_by', models.CharField(max_length=255)),
                ('shipping_address', models.TextField()),
                ('mobile', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('amount', models.PositiveBigIntegerField()),
                ('subtotal', models.PositiveBigIntegerField()),
                ('order_status', models.CharField(choices=[('pending', 'pending'), ('cancel', 'cancel'), ('complete', 'complete')], default='pending', max_length=50)),
                ('payment_method', models.CharField(choices=[('paystack', 'paystack'), ('paypal', 'paypal'), ('transfer', 'transfer')], default='paystack', max_length=50)),
                ('payment_complete', models.BooleanField(default=False)),
                ('ref', models.CharField(max_length=255, null=True, unique=True)),
                ('userlisting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.userlisting')),
            ],
        ),
        migrations.AddField(
            model_name='listing',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.property'),
        ),
    ]
